In [1]:
import numpy as np

In [2]:
x = np.array([
    [10, 12, 14, 16, 18],
    [20, 22, 24, 26, 28],
    [30, 32, 34, 36, 38],
    [40, 42, 44, 46, 48]
])


In [6]:
# Display the shape, size, and datatype of the array.
    
print(x.shape)
print(x.size)
print(type(x))

(4, 5)
20
<class 'numpy.ndarray'>


In [43]:
# Find the sum of all elements in the dataset.
print(np.sum(x))

231


In [8]:
# Create a 1-D NumPy array that contains only even values.
even_values = x[x % 2 == 0]
print("Even values-1D :", even_values)

Even values-1D : [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [9]:
#	Count the total number of even elements.
print("Total number of even elements:",even_values.size)

Total number of even elements: 20


In [13]:
# Extract the third column.
# Extract the second row.
# Extract a sub-matrix consisting of rows 2–3 and columns 3–5.
third_column = x[:, 2]
print("Third column:\n", third_column)

second_row = x[1,:]
print("Second row:\n", second_row)

sub_matrix = x[1:3, 2:5]
print("Sub-matrix:\n", sub_matrix)

Third column:
 [14 24 34 44]
Second row:
 [20 22 24 26 28]
Sub-matrix:
 [[24 26 28]
 [34 36 38]]


In [15]:
# Replace all values greater than 30 with −1.
x[x>30]=-1
print(x)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [19]:
# Set the fourth row to [1, 2, 3, 4, 5].
x[3]=[1,2,3,4,5]
print(x)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [ 1  2  3  4  5]]


In [25]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
scores = np.array([126, 115, 130, 141, 132])

In [28]:
less_130=scores[scores<130]
print(less_130)

[126 115]


In [29]:
statira_scores=scores[names=="Statira"]
print(statira_scores)


[115 141]


In [30]:
roxana_scores=scores[names=="Roxana"]
print(roxana_scores +10)


[136 140 142]


# Pandas

In [38]:
import pandas as pd

data = {
    "Population": [1400000, 331000000, 138000000, 67000000],
    "Capital": ["New Delhi", "Washington D.C.", "Tokyo", "Paris"]
}
df = pd.DataFrame(data, index=["India", "USA", "Japan", "France"])
print(df)


        Population          Capital
India      1400000        New Delhi
USA      331000000  Washington D.C.
Japan    138000000            Tokyo
France    67000000            Paris


In [39]:
# 1. Display first few rows
print("First few rows:\n", df.head())

# 2. Display DataFrame info and data types
print("\n DataFrame Info:")
print(df.info())

print("\nData Types:\n", df.dtypes)


First few rows:
         Population          Capital
India      1400000        New Delhi
USA      331000000  Washington D.C.
Japan    138000000            Tokyo
France    67000000            Paris

 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, India to France
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Population  4 non-null      int64 
 1   Capital     4 non-null      object
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes
None

Data Types:
 Population     int64
Capital       object
dtype: object


In [40]:
# 1. Display population of a specific country (example: India)
print("Population of India:", df.loc["India", "Population"])

# 2. Filter countries with population > 100 million
filtered = df[df["Population"] > 100000000]
print("\nCountries with population > 100 million:\n", filtered)


Population of India: 1400000

Countries with population > 100 million:
        Population          Capital
USA     331000000  Washington D.C.
Japan   138000000            Tokyo


In [41]:
# 1. Add new column GDP 
df["GDP"] = [3.7, 25.0, 4.2, 2.9]
print("\nAfter adding GDP column:\n", df)

# 2. Rename a column (Population → Total_Population)
df.rename(columns={"Population": "Total_Population"}, inplace=True)
print("\nAfter renaming column:\n", df)

# 3. Remove one column (remove Capital column)
df.drop(columns=["Capital"], inplace=True)
print("\nAfter removing Capital column:\n", df)



After adding GDP column:
         Population          Capital   GDP
India      1400000        New Delhi   3.7
USA      331000000  Washington D.C.  25.0
Japan    138000000            Tokyo   4.2
France    67000000            Paris   2.9

After renaming column:
         Total_Population          Capital   GDP
India            1400000        New Delhi   3.7
USA            331000000  Washington D.C.  25.0
Japan          138000000            Tokyo   4.2
France          67000000            Paris   2.9

After removing Capital column:
         Total_Population   GDP
India            1400000   3.7
USA            331000000  25.0
Japan          138000000   4.2
France          67000000   2.9


In [42]:
# 1. Sort DataFrame based on population
sorted_df = df.sort_values(by="Total_Population")
print("\nSorted by population:\n", sorted_df)

# 2. Find average population
avg_population = df["Total_Population"].mean()
print("\nAverage population:", avg_population)



Sorted by population:
         Total_Population   GDP
India            1400000   3.7
France          67000000   2.9
Japan          138000000   4.2
USA            331000000  25.0

Average population: 134350000.0
